apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-dev
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://github.com/nolet7/linkerd_lab.git
    targetRevision: HEAD
    path: apps/linkerd/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
